"""Core tables: users, reports, incidents, incident_reports, outbox.

Revision ID: 0002
Revises: 0001
Created: 2026-08-13

Written by hand rather than autogenerated. Autogenerate does not understand
GeoAlchemy2's Geography columns well — it tends to emit a second CREATE INDEX for the
spatial index it thinks is missing, and it cannot express the partial index on the
outbox at all.
"""
from __future__ import annotations

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from geoalchemy2 import Geography

revision: str = "0002"
down_revision: Union[str, None] = "0001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

WGS84 = 4326

USER_ROLES = ("commuter", "officer", "admin")
INCIDENT_TYPES = ("accident", "flood", "closure", "signal_outage", "roadworks", "surface_defect")
INCIDENT_STATUSES = ("reported", "corroborated", "verified", "assigned", "resolved")


def _in(column: str, values: tuple[str, ...]) -> str:
    joined = ", ".join(f"'{v}'" for v in values)
    return f"{column} IN ({joined})"


def upgrade() -> None:
    # --- users ---------------------------------------------------------------
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("email", sa.String(320), nullable=False),
        sa.Column("password_hash", sa.String(128), nullable=False),
        sa.Column("display_name", sa.String(80), nullable=False),
        sa.Column("role", sa.String(32), nullable=False),
        sa.Column("reputation", sa.Float(), nullable=False, server_default="0.5"),
        sa.Column("reports_confirmed", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("reports_contradicted", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.UniqueConstraint("email", name="uq_users_email"),
        sa.CheckConstraint(_in("role", USER_ROLES), name="ck_users_role"),
        sa.CheckConstraint("reputation >= 0.0 AND reputation <= 1.0", name="ck_users_reputation_range"),
        sa.CheckConstraint("reports_confirmed >= 0", name="ck_users_confirmed_non_negative"),
        sa.CheckConstraint("reports_contradicted >= 0", name="ck_users_contradicted_non_negative"),
    )
    op.create_index("ix_users_email", "users", ["email"])

    # --- reports (immutable) --------------------------------------------------
    op.create_table(
        "reports",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("reporter_id", sa.Uuid(), nullable=False),
        sa.Column("incident_type", sa.String(32), nullable=False),
        sa.Column(
            "location",
            Geography(geometry_type="POINT", srid=WGS84, spatial_index=False),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("idempotency_key", sa.String(64), nullable=True),
        sa.Column("contradicts_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["reporter_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["contradicts_id"], ["reports.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("idempotency_key", name="uq_reports_idempotency_key"),
        sa.CheckConstraint(_in("incident_type", INCIDENT_TYPES), name="ck_reports_incident_type"),
    )
    op.create_index("ix_reports_type_occurred", "reports", ["incident_type", "occurred_at"])
    op.create_index("ix_reports_received_at", "reports", ["received_at"])
    op.create_index("ix_reports_reporter", "reports", ["reporter_id"])
    # GiST: the index type that makes "everything within 300 metres of here" fast.
    # A plain btree cannot answer that question — it only orders one dimension.
    op.create_index("ix_reports_location", "reports", ["location"], postgresql_using="gist")

    # --- incidents (projection) ----------------------------------------------
    op.create_table(
        "incidents",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("incident_type", sa.String(32), nullable=False),
        sa.Column(
            "centroid",
            Geography(geometry_type="POINT", srid=WGS84, spatial_index=False),
            nullable=False,
        ),
        sa.Column("first_reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_reported_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False, server_default="0.0"),
        sa.Column("report_count", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("status", sa.String(32), nullable=False, server_default="reported"),
        sa.Column("assigned_to_id", sa.Uuid(), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.ForeignKeyConstraint(["assigned_to_id"], ["users.id"], ondelete="SET NULL"),
        sa.CheckConstraint(_in("incident_type", INCIDENT_TYPES), name="ck_incidents_incident_type"),
        sa.CheckConstraint(_in("status", INCIDENT_STATUSES), name="ck_incidents_status"),
        sa.CheckConstraint("confidence >= 0.0 AND confidence <= 1.0", name="ck_incidents_confidence_range"),
        sa.CheckConstraint("report_count >= 0", name="ck_incidents_report_count_non_negative"),
        sa.CheckConstraint("last_reported_at >= first_reported_at", name="ck_incidents_time_order"),
    )
    op.create_index("ix_incidents_type_status", "incidents", ["incident_type", "status"])
    op.create_index("ix_incidents_last_reported", "incidents", ["last_reported_at"])
    op.create_index("ix_incidents_centroid", "incidents", ["centroid"], postgresql_using="gist")

    # --- incident_reports (projection) ---------------------------------------
    op.create_table(
        "incident_reports",
        sa.Column("incident_id", sa.Uuid(), primary_key=True),
        sa.Column("report_id", sa.Uuid(), primary_key=True),
        sa.Column("weight", sa.Float(), nullable=False, server_default="0.0"),
        sa.ForeignKeyConstraint(["incident_id"], ["incidents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["report_id"], ["reports.id"], ondelete="CASCADE"),
        # A report may belong to at most one incident. If clustering ever tries to
        # place one in two, the database refuses. The bug surfaces as an error rather
        # than as a quietly double-counted confidence score.
        sa.UniqueConstraint("report_id", name="uq_incident_reports_report"),
    )
    op.create_index("ix_incident_reports_incident", "incident_reports", ["incident_id"])

    # --- outbox ---------------------------------------------------------------
    op.create_table(
        "outbox",
        sa.Column("id", sa.Uuid(), primary_key=True),
        sa.Column("aggregate_type", sa.String(40), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(60), nullable=False),
        sa.Column("payload", sa.dialects.postgresql.JSONB(), nullable=False),
        sa.Column("idempotency_key", sa.String(128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False, server_default=sa.func.now()),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.UniqueConstraint("idempotency_key", name="uq_outbox_idempotency_key"),
        sa.CheckConstraint("attempts >= 0", name="ck_outbox_attempts_non_negative"),
    )
    # Partial index. The worker only ever asks for unprocessed rows, so the index
    # stays small however many processed rows pile up behind it.
    op.create_index(
        "ix_outbox_unprocessed",
        "outbox",
        ["created_at"],
        postgresql_where=sa.text("processed_at IS NULL"),
    )


def downgrade() -> None:
    op.drop_table("outbox")
    op.drop_table("incident_reports")
    op.drop_table("incidents")
    op.drop_table("reports")
    op.drop_table("users")
